
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: glueops-cert-letsencrypt-prod
  namespace: glueops-core-cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: glueops-cert-letsencrypt-prod
    solvers:
      {{ index (index .Values "cert-manager") "solvers"}}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: glueops-cert-letsencryt-nonprod
  namespace: glueops-core-cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: glueops-cert-letsencrypt-nonprod
    solvers:
      {{ index (index .Values "cert-manager") "solvers"}}