apiVersion: v1
data:
  key.json: {{ index (index .Values "cert-manager") "google_cloud_service_account_key" }}
kind: Secret
metadata:
  name: cloud-dns-svc-acct
  namespace: glueops-core-cert-manager
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: glueops-cert-letsencrypt-prod
  namespace: glueops-core-cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: glueops-cert-letsencrypt-prod
    solvers:
    - dns01:
        cloudDNS:
          project: {{ index (index .Values "cert-manager") "google_cloud_project_id"  }}
          serviceAccountSecretRef: 
            name: cloud-dns-svc-acct
            key: key.json
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: glueops-cert-letsencryt-nonprod
  namespace: glueops-core-cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: glueops-cert-letsencrypt-nonprod
    solvers:
    - dns01:
        cloudDNS:
          project: {{ index (index .Values "cert-manager") "google_cloud_project_id"  }}
          serviceAccountSecretRef: 
            name: cloud-dns-svc-acct
            key: key.json