---
apiVersion: v1
data:
{{- if .Values.cloud.enable.aws }}
    {{- with .Values.cloud.credentials.aws }}
      {{- toYaml . | nindent 2 }}
    {{- end }}
{{- end }}
{{- if .Values.cloud.enable.gcp }}
    {{- with .Values.cloud.credentials.gcp }}
      {{- toYaml . | nindent 2 }}
    {{- end }}
{{- end }}
kind: Secret
metadata:
  name: CLOUD_CREDENTIALS
type: Opaque
{{- end }}
---