apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    cert-manager.io/cluster-issuer: glueops-cert-zerossl-prod
    kubernetes.io/ingress.class: "external-ingress-nginx"
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: echo-tls
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: 8080
