apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.domain }}
    external-dns.alpha.kubernetes.io/ttl: "30"
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 3000