# Default values for glueops-cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cert-manager:
  installCRDs: false
  google_cloud_project_id: ""
  google_cloud_service_account_key: ""

