# Default values for glueops-cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cert-manager:
  installCRDs: false
  solvers: |-
    http01:
            ingress:
              class: nginx